name: Deploy Trainer Panel
 
on:
  push:
    branches:
      - latest
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/trainer-source
 
            git fetch origin
            git reset --hard origin/latest
 
            npm install
            npm run build
 
            rm -rf /var/www/trainer.learnntrade.com/*
            cp -r dist/* /var/www/trainer.learnntrade.com/
 
            chown -R www-data:www-data /var/www/trainer.learnntrade.com
            chmod -R 755 /var/www/trainer.learnntrade.com
 
            echo "🚀 Deployment completed"